language: java
jdk:
- oraclejdk8

#branches:
#  only:
#  - develop

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'

script: "./mvn clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
    - dkeplusi.dev@gmail.com
    - gyummy0917@gmail.com